### ISSUE TITLE
karma-bro & `TypeError: 'undefined' is not a function (evaluating 'require.resolve(__filename)')`

### ISSUE THREAD

**Issue by franleplant** [bendrucker/proxyquire-universal#11]
Hi!
    I was not able to run tests using proxyquire with karma-browserify:

**karma config**
```javascript
module.exports = function(karma) {
  karma.set({

    frameworks: [ 'browserify', 'jasmine' ],
    files: ['./js/**/*.test.js'],
    preprocessors: {
      './js/**/*.test.js': [ 'browserify' ]
    },
    browsers: [
        'PhantomJS'
    ],

    singleRun: true,

    browserify: {
      debug: true,
      transform: [ 'babelify' ],
      plugin: ['proxyquire-universal']
    }
  });
}
```

**test**

```javascript

var proxyquire = require('proxyquire');

var firebaseMock = {...}
 
var osutils = proxyquire('./osutils.js', { firebase: firebaseMock});
```

But here is the good news, this is the way I found to get it working:

```javascript
// use this:
var proxyquire = require('proxyquireify')(require);

// instead of this
var proxyquire = require('proxyquireify');
```

Is this somewhat documented? Am I doing something wrong?

Thanks a lot!
Fran

**Comment by bendrucker** [comment]
I need a minimal reproduction that I can run in order to investigate further.

**Comment by franleplant** [comment]
hm, interesting, I was trying to create a minimal reproduction but after removing React and Babelify from the stack the error disappeared.

Perhaps there is some problems in the interaction with React and/or Babelify.

**Comment by bendrucker** [comment]
React itself is built with Babel so that would be weird. Babel often does rewrite identifiers but I doubt that's the issue here. 

The following isn't valid, as you've noted:

```js
var proxyquire = require('proxyquireify');
```

All proxyquire-universal does is hook up proxyquireify to browserify and then replace `require('proxyquire')` with `require('proxyquireify')(require)`. If you can manage to reproduce this (including an issue interacting with babelify) I'm happy to reopen and take a look. I use babelify but I don't think I've actually used pquire-universal in the same project.

**Comment by franleplant** [comment]
Yes, sounds reasonable, if I isolate the problem I will ping you, thanks for your help!

Fran
